server:
  port: 8080

---
spring:
  profiles: dev, staging

image:
  file:
    directory: 'D:/resources/static/images'


---
spring:
  profiles: prod

image:
  file:
    directory: '/resources/static/images'

