
spring:
  profiles: dev, staging

image:
  file:
    directory: 'D:\www\masterpiece\static\'
    marker: '<@@MASTERPIECE_CLUB_IMAGE>'

---
spring:
  profiles: prod

image:
  file:
    directory: ''
    marker: ''
