
spring:
  profiles: dev, staging

image:
  file:
    directory: 'D:\www\masterpiece\static\'


---
spring:
  profiles: prod

image:
  file:
    scheme: 'http'
    host: 'masterpiece-1st.com'
    directory: '/static/images'

