server:
  port: 8080

---
spring:
  profiles: dev, staging

image:
  file:
    directory: 'D:/resource/static/images'

server:
  port: 8085

---
spring:
  profiles: prod

image:
  file:
    directory: '/resource/static/images'

