
# spring boot template : freemarker
spring:
  freemarker:
    check-template-location: false
    template-loader-path: classpath:/static/templates
    suffix: .ftl

# default
table:
  user: user
  article: article
  comment: comment

keyword:
  image: '@@GULAGBU_IMAGE'
  video: '@@GULAGBU_VIDEO'