
# spring boot template : freemarker
spring:
  freemarker:
    template-loader-path: classpath:/static/templates
    suffix: .ftl


# logback setting
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate: ERROR
#  file: gulagbu.log

# default
table:
  user: user
  article: article
  comment: comment