spring:
  freemarker:
    check-template-location: false
    template-loader-path: classpath:/static/templates
    suffix: .ftl
  banner:
    location: classpath:banner/banner.txt
  profiles:
    active: prod
    include:
      - default
      - security