# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Masterpiece WEB CI

on:
  push:
    branches:
      - develop/web
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    # frontend (vue)
    - name: Run pwd
      run: pwd
    - name: Move to Frontend Directory
      run: cd movie-masterpiece-club-web/frontend
    - name: Use Node.js ${{matrix.node-version}}
      with:
        - node-version: ${{matrix.node-version}}
    - name: npm install
      run: npm install
    - name: vue frontend build [prod]
      run: npm run build:prod

    - name: Move to Root Directory
      run: cd ../../

    # backend
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Restoring gradle wrapper
      run: gradle wrapper --gradle-version=6.3 --distribution-type=bin
#      run: gradle wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :movie-masterpiece-club-web:bootJar
