# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Masterpiece WEB CI

on:
  push:
    branches:
      - develop/web
#  pull_request:
#    branches: [ master ]

jobs:
  frontend_build_job:
    name: FrontEnd Build By Npm (Vue)
    runs-on: ubuntu-latest
    env:
      working-directory: ./movie-masterpiece-club-web/frontend/
    build:
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.16.1'
            registry-url: 'https://registry.npmjs.org'
        - name: frontend build
          run: |
            npm install
            npm run build:prod

  backend_build_job:
    # frontend_build_job 이후 실행.
    needs: frontend_build_job
    runs-on: ubuntu-latest
    name: SpringBoot Build By Gradle
    env:
      working-directory: .
    build:
      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Restoring gradle wrapper
          run: gradle wrapper --gradle-version=6.3 --distribution-type=bin
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build with Gradle
          run: ./gradlew :movie-masterpiece-club-web:bootJar
